@startuml
title Task Manager - Use Case Diagram

left to right direction

actor "User" as user

rectangle "Task Manager System" {
    usecase "Create Account" as UC1
    usecase "Create Task" as UC2
    usecase "View My Tasks" as UC3
    usecase "Complete Task" as UC4
    usecase "Delete Task" as UC5
}

user --> UC1
user --> UC2
user --> UC3
user --> UC4
user --> UC5

UC2 ..> UC1 : <<potrzeba konta>>
UC3 ..> UC1 : <<potrzeba konta>>
UC4 ..> UC2 : <<potrzeba zadania>>
UC5 ..> UC2 : <<potrzeba zadania>>

note right of UC1 : nazwa użytkownika oraz email\muszą być unikalne

note right of UC5 : Nie można usunąć\nukończonych zadań

@enduml